services:
  postgres:
    container_name: postgres-sql
    image: postgres
    environment:
      POSTGRES_USER: diagana
      POSTGRES_PASSWORD: diagana
      #PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5433"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
    - "${PGADMIN_PORT:-5050}:80"
      #- "5050:80"


    networks:
      - postgres
    restart: unless-stopped
#  smtp4dev:
#      image: rnwood/smtp4dev:v3
#      restart: always
#      ports:
#        - 9025:25
        # Change the number before : to the port the web interface should be accessible on
        #- '5000:80'
        # Change the number before : to the port the SMTP server should be accessible on
       #'9081:80 navigateur'
        # Change the number before : to the port the IMAP server should be accessible on


networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: